### ISSUE TITLE
大神请问我这样traing是对的吗

### ISSUE THREAD

**Issue by kelvinng2017** [zake7749/word2vec-tutorial#2]
![image](https://user-images.githubusercontent.com/24961569/61215226-c9fa2100-a73c-11e9-8656-902277503c18.png)
1各小时才出来0.10%

**Comment by GoatWang** [comment]
哇，我這兩年前寫的文章，都忘記了，如果可以跑得動，就等結果看相似的詞彙是不是跟我們的理解很像，如果是就沒錯了！


 
王選仲 Jeremy Wang
研發工程師 R&D Engineer  
｜Office: +886 2-8978-3797 #219
｜Mobile: +886 921-687-452
｜Email: jeremywang@thinktronltd.com
｜Add: 10087 台北市中正區思源街18號卓越研究大樓3樓309室
｜Website｜Facebook｜Instagram

**Comment by kelvinng2017** [comment]
謝謝

王選仲 <notifications@github.com> 於 2019年7月16日 週二 00:22 寫道：
