### ISSUE TITLE
请问我能拿word2vec.model自己做一個閒聊的聊天機器人嗎

### ISSUE THREAD

**Issue by kelvinng2017** [zake7749/word2vec-tutorial#3]
![image](https://user-images.githubusercontent.com/24961569/61574123-f28f6b80-aaec-11e9-8948-cf6910597ba1.png)

**Comment by GoatWang** [comment]
很難用純粹的w2v做，w2v只能做詞彙相關，閒聊要組織句子要用RNN orLSTM，不過這些技術一般都base on w2v。


 
王選仲 Jeremy Wang
研發工程師 R&D Engineer  
｜Office: +886 2-8978-3797 #219
｜Mobile: +886 921-687-452
｜Email: jeremywang@thinktronltd.com
｜Add: 10087 台北市中正區思源街18號卓越研究大樓3樓309室
｜Website｜Facebook｜Instagram
